import Head from "next/head";
import styled from "styled-components";
import {
  AiOutlineBarChart,
  AiOutlineLineChart,
  AiOutlineUserAdd,
} from "react-icons/ai";

import SalesCard from "components/SalesCard";
import OrdersTable from "components/OrdersTable";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* top cards section */}
      <CardsWrapper>
        {cardsData.map((card) => (
          <SalesCard
            key={card.id}
            title={card.title}
            icon={card.icon}
            background={card.background}
            figure={card.figure}
            increase={card.increase}
          />
        ))}
      </CardsWrapper>

      {/* recent orders */}
      <OrdersTable />
    </>
  );
}

const CardsWrapper = styled.div`
  display: grid;
  gap: 1rem;

  @media (min-width: 425px) {
    grid-template-columns: repeat(2, 1fr);
  }

  @media (min-width: 767px) {
    grid-template-columns: repeat(3, 1fr);
  }
`;

const cardsData = [
  {
    id: 1,
    title: "Total Orders",
    figure: "5,000 units",
    increase: 2,
    background: "#98BDFF",
    icon: <AiOutlineBarChart style={{ fontSize: "2.5rem" }} />,
  },
  {
    id: 2,
    title: "Total Sales",
    figure: "Rs. 80,000",
    increase: 4,
    background: "#F3797E",
    icon: <AiOutlineLineChart style={{ fontSize: "2.5rem" }} />,
  },
  {
    id: 3,
    title: "Total Users",
    figure: "960 users",
    increase: 20,
    background: "#7DA0FA",
    icon: <AiOutlineUserAdd style={{ fontSize: "2.5rem" }} />,
  },
];
